---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php package
    package:
      name: 
        - "{{ apache_p }}"
        - "{{ php_p }}"
      state: latest
      update_cache: yes
